import React,{useEffect,useState} from 'react';
import api from '../../../../services/api';
import {documentError} from '../intakeCreationFiles';
export default function AttachmentPreview({file,path,name,mime}){
 const[open,setOpen]=useState(false),[src,setSrc]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const kind=(mime||file?.type||'').toLowerCase();const image=kind.startsWith('image/'),video=kind.startsWith('video/'),pdf=kind==='application/pdf'||name?.toLowerCase().endsWith('.pdf');
 useEffect(()=>{if(!open)return;let live=true,url;setBusy(true);setError('');setSrc('');(async()=>{try{const blob=file|| (await api.get(path,{responseType:'blob'})).data;if(!live)return;if(image){const value=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(new Error('No se pudo abrir la imagen.'));reader.readAsDataURL(blob);});if(live)setSrc(value);}else{url=URL.createObjectURL(blob);if(live)setSrc(url);}}catch(e){const message=await documentError(e);if(live)setError(message);}finally{if(live)setBusy(false);}})();return()=>{live=false;if(url)URL.revokeObjectURL(url);};},[open,file,path,image]);
 const download=async()=>{try{const blob=file||(await api.get(path,{responseType:'blob'})).data;const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name||file?.name||'Documento';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}catch(e){setError(await documentError(e));}};
 return <div className="space-y-2 min-w-0"><div className="flex flex-wrap gap-3 text-sm">{(image||video||pdf)&&<button type="button" onClick={()=>setOpen(!open)} className="accent-text underline">{open?'Cerrar vista previa':'Vista previa'}</button>}<button type="button" onClick={download} className="accent-text underline">Descargar {name||file?.name}</button></div>{open&&busy&&<p className="text-xs">Cargando vista previa…</p>}{open&&src&&(image?<img src={src} alt={name||file?.name||'Evidencia'} className="max-h-64 max-w-full rounded-xl object-contain bg-white" onError={()=>setError('El navegador no pudo mostrar esta imagen. Puedes descargar el archivo original.')}/>:video?<video src={src} controls className="max-h-64 w-full"/>:<iframe title={'Vista previa de '+(name||file?.name||'PDF')} src={src} className="w-full h-96 border rounded-xl bg-white"/>)}{!image&&!video&&!pdf&&<p className="text-xs text-gray-500">Este formato se consulta descargando el archivo.</p>}{error&&<p role="alert" className="text-sm">{error}</p>}</div>;
}
