import React from 'react';
import EquipmentIntakeFields,{emptyEquipmentIntake} from './EquipmentIntakeFields';
import {IntakePhotos} from './IntakeCreationDocuments';
export const newEquipment=()=>({...emptyEquipmentIntake(),id:crypto.randomUUID()});
export const emptyEquipmentList=()=>{const item=newEquipment();return {...item,equipments:[item]};};
export default function EquipmentIntakeList({value,onChange,readOnly=false,files=[],onPhotosChange,existing=[],onRemoveExisting,allowCollectionChanges=true}){
 const items=value?.equipments|| (value?.equipment_received?[value]:[]);
 const change=next=>onChange({...next[0],equipment_received:!!value?.equipment_received,equipments:next.map(e=>({...e,equipment_received:!!value?.equipment_received}))});
 return <section className="space-y-4"><label className="flex gap-2 items-center font-semibold text-sm"><input type="checkbox" checked={!!value?.equipment_received} disabled={readOnly||!allowCollectionChanges||existing.length>0} onChange={e=>{onPhotosChange?.([]);onChange({...value,equipment_received:e.target.checked,equipments:items.map(item=>({...item,equipment_received:e.target.checked}))});}}/>El cliente entrega uno o varios equipos para recibirlos en taller</label>{(value?.equipment_received||items.length)?<>{items.map((item,index)=>{const id=item.id||null;const current=files.filter(f=>f.equipment_id===id);const saved=existing.filter(f=>f.equipment_id===id||(!f.equipment_id&&index===0));return <article key={id||index} className="border rounded-xl p-4 space-y-3"><header className="flex justify-between gap-2"><h4 className="font-bold">Equipo {index+1}{item.equipment_type?` · ${item.equipment_type}`:''}</h4>{!readOnly&&allowCollectionChanges&&(items.length>1||!value?.equipment_received)&&<button type="button" disabled={saved.length>0} className="underline text-sm disabled:opacity-50" onClick={()=>{change(items.filter((_,n)=>n!==index));onPhotosChange?.(files.filter(f=>f.equipment_id!==id));}}>Quitar equipo</button>}</header><EquipmentIntakeFields descriptionOnly={!value?.equipment_received} hideReceivedToggle value={{...item,equipment_received:true}} readOnly={readOnly} onChange={updated=>change(items.map((old,n)=>n===index?{...updated,id:old.id||crypto.randomUUID()}:old))}/>{onPhotosChange&&value?.equipment_received&&<IntakePhotos readOnly={readOnly} files={current} onChange={next=>onPhotosChange([...files.filter(f=>f.equipment_id!==id),...next.map(f=>({...f,equipment_id:id}))])} existing={saved} onRemoveExisting={readOnly?undefined:onRemoveExisting}/>}</article>})}{!readOnly&&allowCollectionChanges&&<button type="button" disabled={items.length>=50} className="accent-fill rounded-xl px-4 py-2 disabled:opacity-50" onClick={()=>{const previous=items[0];change([...items,{...newEquipment(),received_from_name:previous?.received_from_name||value.received_from_name||'',received_from_document:previous?.received_from_document||value.received_from_document||''}]);}}>Agregar otro equipo</button>}<p className="text-sm">{items.length} equipo(s) registrados.</p></>:<div className="space-y-2"><p className="text-sm">Puedes registrar los equipos atendidos sin recibirlos en taller.</p>{!readOnly&&allowCollectionChanges&&<button type="button" className="accent-fill rounded-xl px-4 py-2" onClick={()=>change([newEquipment()])}>Agregar equipo</button>}</div>}</section>;
}
