import React,{useState} from 'react';
import api from '../../../../services/api';
import WorldOfficeDiscoveryModal from './WorldOfficeDiscoveryModal';
const money=(value,currency='COP')=>value===null||value===undefined?'Sin dato':Number(value).toLocaleString('es-CO')+' '+currency;
export default function IntakeInvoicePicker({client,ensureDraft,onLinked,admin,edit=false,initialReference='',selectedInvoice}){
 const[q,setQ]=useState(initialReference),[rows,setRows]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[linked,setLinked]=useState(null),[mappingNeeded,setMappingNeeded]=useState(false),[configure,setConfigure]=useState(false),[warnings,setWarnings]=useState([]);
 const search=async()=>{setBusy(true);setError('');setRows([]);setWarnings([]);try{const r=await api.get('/api/service-orders/worldoffice-invoices',{params:{client_id:client.id,origin:client.origen||'local',q}});setRows(r.data.data||[]);setWarnings(r.data.warnings||[]);setMappingNeeded(false);if(!r.data.data?.length)setError('No se encontraron facturas para este cliente en el origen configurado.');}catch(e){setMappingNeeded(e.response?.data?.code==='WORLDOFFICE_MAPPING_REQUIRED');setError(e.response?.data?.message||'No fue posible consultar World Office.');}finally{setBusy(false);}};
 const link=async row=>{setBusy(true);setError('');try{if(edit){const r=await api.get('/api/service-orders/worldoffice-invoice-details',{params:{client_id:client.id,origin:client.origen||'local',reference:row.invoice_reference,source_company:row.source_company,source_id:row.source_id}});setLinked(r.data);onLinked(r.data);return;}const i=await ensureDraft();const r=await api.post(`/api/service-orders/intakes/${i.id}/link-invoice`,{reference:String(row.invoice_reference),invoice_id:row.invoice_id,source_company:row.source_company,source_id:row.source_id});setLinked(r.data);onLinked(r.data);}catch(e){setError(e.response?.data?.message||'No se pudo vincular la factura.');}finally{setBusy(false);}};
 return <section className="rounded-xl border p-4 space-y-3"><h4 className="font-semibold">Factura del servicio</h4><p className="text-sm">Busca y selecciona la factura de World Office para vincular sus datos. Puedes buscar por número o por referencia completa.</p>{admin&&<><div className="flex gap-2"><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();if(!busy)search();}}} placeholder="Número, prefijo o factura completa" className="min-w-0 flex-1 min-h-11 rounded-xl border bg-white dark:bg-gray-950 px-3"/><button type="button" disabled={busy} onClick={search} className="rounded-xl border px-3">{busy?'Consultando…':'Buscar en World Office'}</button></div>{rows.map((r,i)=><div key={i} className="border rounded-xl p-3 space-y-2"><strong>{r.invoice_reference}</strong><p className="text-sm">{r.invoice_date&&new Date(r.invoice_date).toLocaleDateString('es-CO',{timeZone:'America/Bogota'})} {r.company_name&&' · '+r.company_name}</p>{r.total_amount!=null&&<p className="text-sm">{r.source==='sales_inventory_movements'?'Subtotal + IVA':'Total'}: {money(r.total_amount,r.currency||'COP')} · Saldo: {money(r.balance_amount,r.currency||'COP')}</p>}<button type="button" disabled={busy} onClick={()=>link(r)} className="accent-text underline text-sm">Vincular esta factura</button></div>)}{mappingNeeded&&<button type="button" onClick={()=>setConfigure(true)} className="accent-text underline">Configurar origen de facturas aquí</button>}<WorldOfficeDiscoveryModal open={configure} onClose={()=>setConfigure(false)} onMappingChanged={()=>{setConfigure(false);search();}}/></>}{(linked||selectedInvoice)&&<p className="text-sm accent-text">Factura {(linked||selectedInvoice).reference} seleccionada. Sus datos aparecen en Resumen.{edit?' Se guardará al pulsar Guardar cambios.':''}</p>}{warnings.map(w=><p key={w} role="status" className="text-sm">{w}</p>)}{error&&<p role="alert" className="text-sm">{error}</p>}</section>;
}
