import React,{useEffect,useState} from 'react';
import api from '../../../../services/api';
import ResponsiveSignaturePad from '../../../../components/ui/ResponsiveSignaturePad';
import AttachmentPreview from './AttachmentPreview';
import {openIntakeDocument} from '../intakeCreationFiles';
export function IntakePhotos({files,onChange,existing=[],onRemoveExisting}){
 const[error,setError]=useState('');const pick=e=>{setError('');const added=[];for(const file of Array.from(e.target.files||[])){if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>8*1024*1024){setError('Usa fotos JPG, PNG o WEBP de máximo 8 MB.');continue;}if(files.length+existing.length+added.length>=3){setError('Máximo 3 fotos de ingreso.');break;}added.push({key:crypto.randomUUID(),file});}onChange([...files,...added]);e.target.value='';};
 return <section className="space-y-2 mt-4"><label className="block font-semibold text-sm">Fotos de ingreso (opcional, máximo 3)<input className="block mt-2 w-full" type="file" accept="image/png,image/jpeg,image/webp" multiple onChange={pick} disabled={files.length+existing.length>=3}/></label>{error&&<p role="alert" className="text-sm">{error}</p>}{files.map(f=><Photo key={f.key} entry={f} onRemove={()=>onChange(files.filter(x=>x.key!==f.key))}/>)}{existing.map(f=><div key={f.id} className="flex gap-2 text-sm"><AttachmentPreview path={`/api/service-orders/intakes/${f.intake_id}/creation-documents/${f.id}`} name={f.name} mime={f.mime}/>{onRemoveExisting&&<button type="button" onClick={()=>onRemoveExisting(f.id)}>Quitar</button>}</div>)}<p className="text-xs text-gray-500">Las fotos se guardan con la solicitud y pasan a las evidencias iniciales de la orden.</p></section>;
}
function Photo({entry,onRemove}){const[url,setUrl]=useState('');useEffect(()=>{let live=true;const reader=new FileReader();reader.onload=()=>{if(live)setUrl(reader.result);};reader.readAsDataURL(entry.file);return()=>{live=false;if(reader.readyState===1)reader.abort();};},[entry.file]);return <div className="flex items-center gap-3"><img src={url||undefined} className="w-20 h-20 object-cover rounded-xl" alt={entry.file.name}/><AttachmentPreview file={entry.file} name={entry.file.name}/><button type="button" onClick={onRemove} className="underline text-sm">Quitar</button></div>;}
export function IntakeAcceptance({client,ensureDraft,revision,signedRevision,onSigned,act,signature,onSignature,isEdit,scope,conditions}){
 const[busy,setBusy]=useState(false),[error,setError]=useState(''),[clear,setClear]=useState(0),[history,setHistory]=useState([]),[imported,setImported]=useState(false);
 const sign=async()=>{setBusy(true);setError('');try{if(!signature)throw new Error('Dibuja la firma del cliente.');const intake=await ensureDraft();const r=await api.post(`/api/service-orders/intakes/${intake.id}/sign-acceptance`,{signature});onSigned(revision,{...r.data,intake_id:intake.id});await openIntakeDocument(`/api/service-orders/intakes/${intake.id}/acceptance-acts/${r.data.id}`,'Acta-aceptacion.pdf');}catch(e){setError(e.response?.data?.message||e.message);}finally{setBusy(false);}};
 const loadHistory=async()=>{try{const r=await api.get(`/api/clients/${client.id}/acceptance-history`,{params:{origin:client.origen||'local'}});setHistory(r.data.data||[]);if(!r.data.data?.length)setError('Este cliente aún no tiene aceptaciones firmadas.');}catch(e){setError(e.response?.data?.message||'No se pudo cargar el historial.');}};
 if(isEdit)return <p className="text-sm">Las actas firmadas de esta orden se consultan en Documentos PDF. Una firma anterior conserva las condiciones que fueron aceptadas en esa versión.</p>;
 return <section className="border rounded-xl p-4 space-y-3"><h4 className="font-semibold">Acta de aceptación y firma del cliente</h4><details open><summary className="text-sm font-semibold">Condiciones que firma</summary><p className="text-sm whitespace-pre-wrap mt-2">{scope}</p><p className="text-sm whitespace-pre-wrap mt-2">{conditions}</p></details>{signedRevision===revision&&act?<><img src={signature} className="w-full max-w-sm h-40 object-contain bg-white rounded-xl" alt="Firma de aceptación"/></>:<ResponsiveSignaturePad clearToken={clear} onChange={(canvas,hasInk)=>{if(hasInk){setImported(false);onSignature(canvas.toDataURL('image/png'));}}}/>}<button type="button" disabled={busy} onClick={()=>{onSignature('');onSigned('',null);setClear(clear+1);setImported(false);setError('');}} className="text-sm underline">Borrar firma</button><p className="text-xs text-gray-500">Puedes firmar con mouse, dedo o lápiz de una tableta digitalizadora reconocida por el navegador. Para dispositivos que exportan la firma, adjunta su imagen PNG.</p><label className="block text-sm">Importar firma de tableta (PNG)<input type="file" accept="image/png" disabled={busy} onChange={e=>{const f=e.target.files?.[0];e.target.value='';if(!f)return;if(f.type!=='image/png'||f.size>2*1024*1024){setError('Usa una firma PNG de máximo 2 MB.');return;}const reader=new FileReader();reader.onload=()=>{onSignature(reader.result);onSigned('',null);setImported(true);setError('');};reader.readAsDataURL(f);}}/></label>{imported&&signature&&signedRevision!==revision&&<img src={signature} alt="Firma importada" className="h-28 bg-white object-contain"/>}<p className="text-xs text-gray-500">La firma y el acta se vinculan al cliente y a la identificación de quien acepta. Cada nueva aceptación requiere su propia firma.</p>{signedRevision===revision&&act?<><p className="text-sm accent-text">Aceptación firmada y guardada.</p><button type="button" className="underline" onClick={()=>openIntakeDocument(`/api/service-orders/intakes/${act.intake_id}/acceptance-acts/${act.id}`,'Acta-aceptacion.pdf')}>Descargar acta firmada</button></>:<button type="button" disabled={busy} onClick={sign} className="accent-fill rounded-xl px-3 py-2">{busy?'Generando acta…':'Firmar y generar acta de aceptación'}</button>}<button type="button" onClick={loadHistory} className="block underline text-sm">Ver aceptaciones anteriores de este cliente</button>{history.map(h=><p key={h.id} className="text-xs">{h.signer_name} · {h.signer_document} · {new Date(h.captured_at).toLocaleString('es-CO',{timeZone:'America/Bogota'})}</p>)}{error&&<p role="alert" className="text-sm">{error}</p>}</section>;
}
