import React, {useEffect,useState} from 'react';
import api from '../../../../services/api';
export default function ServiceInventoryRequirements({value=[],onChange}) {
 const editable=!!onChange;
 const [query,setQuery]=useState(''),[items,setItems]=useState([]),[error,setError]=useState(''),[loading,setLoading]=useState(false);
 useEffect(()=>{if(!editable)return;let active=true;const timer=setTimeout(async()=>{setLoading(true);try{const r=await api.get('/api/tipos-servicio/inventory-catalog',{params:{q:query}});if(active){setItems(r.data);setError('');}}catch(e){if(active)setError(e.response?.data?.message||'No se pudo cargar el inventario.');}finally{if(active)setLoading(false);}},250);return()=>{active=false;clearTimeout(timer);};},[query,editable]);
 const selected=new Set(value.map(i=>i.product_id));
 return <section className="space-y-3 border rounded-xl p-3"><h4 className="font-semibold">Inventario necesario</h4><p className="text-xs text-gray-500">Artículos y cantidades previstos para este tipo de servicio. Las existencias se asignan y descuentan cuando el técnico principal acepta el servicio.</p>{onChange&&<><label className="block text-sm">Buscar artículo<input className="w-full border rounded-lg px-3 py-2 bg-transparent" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Nombre o código del inventario"/></label>{loading&&<p className="text-sm">Buscando inventario…</p>}{error&&<p role="alert">{error}</p>}<div className="max-h-40 overflow-auto">{items.filter(i=>!selected.has(i.product_id)).map(i=><button type="button" key={i.product_id} className="block w-full text-left border-b px-2 py-2 text-sm" onClick={()=>onChange([...value,{...i,quantity:1}])}>{i.codigo} · {i.nombre}<span className="block text-xs text-gray-500">Disponible: {i.stock_actual} · {i.kind==='tool'?'Herramienta':i.kind==='supply'?'Insumo':'Clasifica este artículo en Inventario de taller'}</span></button>)}{!loading&&!error&&!items.length&&<p className="text-sm">No hay artículos disponibles en el catálogo.</p>}</div></>}{!value.length&&<p className="text-sm">Sin artículos configurados.</p>}<ul className="space-y-2">{value.map(item=><li key={item.product_id} className="flex flex-wrap gap-2 items-center border rounded-lg p-2"><span className="min-w-0 flex-1 text-sm"><strong>{item.nombre}</strong><span className="block text-xs">{item.codigo}{item.stock_actual!==undefined&&` · Disponible: ${item.stock_actual}`}</span>{Number(item.stock_actual)<Number(item.quantity)&&<span className="block text-xs">Las existencias actuales no cubren la cantidad prevista.</span>}</span>{onChange?<><label className="text-xs">Cantidad<input aria-label={`Cantidad de ${item.nombre}`} type="number" min="1" max="100000" step="1" required className="block w-20 border rounded-lg p-2 bg-transparent" value={item.quantity} onChange={e=>onChange(value.map(i=>i.product_id===item.product_id?{...i,quantity:e.target.value}:i))}/></label><button type="button" aria-label={`Quitar ${item.nombre}`} className="text-sm underline" onClick={()=>onChange(value.filter(i=>i.product_id!==item.product_id))}>Quitar</button></>:<span className="text-sm">Cantidad: {item.quantity}</span>}</li>)}</ul></section>;
}
