import React,{useEffect,useState,useRef} from 'react';import api from '../../../../services/api';
export default function ServiceActivityModal({service,onClose}){
 const requestRef=useRef(0);
 const [rows,setRows]=useState([]);const[actors,setActors]=useState([]);const[actor,setActor]=useState('');const[error,setError]=useState('');const[loading,setLoading]=useState(false);const[more,setMore]=useState(false);
 const load=async(append=false)=>{if(!service)return;const request=++requestRef.current;setLoading(true);setError('');try{const response=await api.get(`/api/service-orders/${service.id}/activity-history`,{params:{actor,offset:append?rows.length:0}});if(request!==requestRef.current)return;setRows(previous=>append?[...previous,...response.data.data]:response.data.data);setActors(response.data.actors||[]);setMore(response.data.has_more);}catch(e){if(request!==requestRef.current)return;setError(e.response?.data?.message||'No se pudo cargar el historial');}finally{if(request===requestRef.current)setLoading(false);}};
 useEffect(()=>{setRows([]);load();return()=>{requestRef.current++;};},[service?.id,actor]);
 if(!service)return null;
 return <div className="workflow-theme fixed inset-0 z-[180] bg-black/60 p-3 flex items-center justify-center"><section className="bg-white dark:bg-gray-900 rounded-2xl w-full max-w-3xl max-h-[90dvh] flex flex-col"><header className="p-4 border-b flex justify-between"><h3 className="font-bold">Historial de acciones · {service.codigo_os}</h3><button onClick={onClose}>Cerrar</button></header><div className="p-4 overflow-auto space-y-3"><div className="flex-wrap flex gap-2"><select aria-label="Filtrar historial por usuario" className="border rounded-lg p-2 bg-transparent flex-1" value={actor} onChange={e=>setActor(e.target.value)}><option value="">Todos los usuarios</option>{actors.map(a=><option key={a.actor_user_id} value={a.actor_user_id}>{a.actor_name}</option>)}</select><button onClick={()=>load()} disabled={loading} className="border rounded-lg p-2">Actualizar</button></div>{error&&<p role="alert" className="text-red-600">{error}</p>}{rows.map(row=><article key={row.id} className="rounded-xl border p-3"><p className="font-semibold">{row.actor_name} · {row.action_label}</p><p className="text-sm whitespace-pre-wrap break-words">{row.detail_text}</p><p className="text-xs text-gray-500">{new Date(row.created_at).toLocaleString('es-CO',{timeZone:'America/Bogota'})}</p>{row.changed_fields?.length>0&&<details className="text-xs mt-2"><summary>Campos registrados</summary><p className="break-words">{row.changed_fields.join(', ')}</p></details>}</article>)}{!rows.length&&!loading&&!error&&<p>Sin acciones registradas.</p>}{loading&&<p>Cargando…</p>}{more&&<button disabled={loading} onClick={()=>load(true)} className="border rounded-lg p-2 w-full">Cargar más acciones</button>}</div></section></div>;
}
