import React,{useState} from 'react';
import api from '../../../../services/api';
import ServiceInventoryRequirements from './ServiceInventoryRequirements';
export default function ServiceTypePicker({types,value,onSelect,onCreated,canCreate}){
 const[q,setQ]=useState(''),[adding,setAdding]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const[draft,setDraft]=useState({nombre:'',descripcion:'',valor_base:0,duracion_estimada:60,categoria:'',inventory_requirements:[]});
 const selectedIds=Array.isArray(value)?value:(value?[value]:[]);
 const selected=types.filter(t=>selectedIds.includes(t.id));
 const create=async()=>{setBusy(true);setError('');try{const r=await api.post('/api/tipos-servicio',{...draft,valor_base:Number(draft.valor_base),duracion_estimada:Number(draft.duracion_estimada),activo:true});onCreated(r.data);setAdding(false);setQ('');}catch(e){setError(e.response?.data?.message||'No se pudo crear el tipo.');}finally{setBusy(false);}};
 const input='w-full min-h-11 rounded-xl border bg-white dark:bg-gray-950 px-3';
 const filtered=types.filter(t=>[t.nombre,t.categoria].join(' ').toLowerCase().includes(q.toLowerCase()));
 return <section className="space-y-3"><label className="block text-sm font-semibold">Tipos de servicio *<input className={input} value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar y agregar tipos de servicio"/></label>{selected.length>0&&<ul className="space-y-2">{selected.map(t=><li key={t.id} className="accent-soft rounded-lg p-2 flex justify-between gap-2"><span>{t.nombre} · {t.duracion_estimada||60} min</span><button type="button" className="underline text-sm" aria-label={`Quitar tipo ${t.nombre}`} onClick={()=>onSelect(t.id)}>Quitar</button></li>)}</ul>}<div role="listbox" aria-label="Tipos de servicio" aria-multiselectable="true" className="max-h-48 overflow-auto rounded-xl border">{filtered.slice(0,50).map(t=><button key={t.id} type="button" role="option" aria-selected={selectedIds.includes(t.id)} onClick={()=>onSelect(t.id)} className={'block w-full text-left px-3 py-2 border-b '+(selectedIds.includes(t.id)?'accent-soft':'')}><span className="font-semibold">{t.nombre}</span><span className="block text-xs text-gray-500">{t.duracion_estimada||60} minutos · {Number(t.valor_base||0).toLocaleString('es-CO')} COP</span></button>)}{!filtered.length&&<p className="p-3 text-sm">No hay coincidencias.</p>}</div>{canCreate&&<button type="button" onClick={()=>{setAdding(!adding);setDraft({...draft,nombre:q});}} className="accent-text underline text-sm">{adding?'Cancelar creación':'Crear tipo de servicio aquí'}</button>}{adding&&<div className="border rounded-xl p-3 space-y-3"><h4 className="font-semibold">Nuevo tipo de servicio</h4>{[['nombre','Nombre'],['descripcion','Descripción / alcance'],['categoria','Categoría (opcional)'],['duracion_estimada','Duración en minutos'],['valor_base','Valor base COP']].map(([k,label])=><label key={k} className="block text-sm">{label}<input type={['duracion_estimada','valor_base'].includes(k)?'number':'text'} min={k==='duracion_estimada'?1:0} className={input} value={draft[k]} onChange={e=>setDraft({...draft,[k]:e.target.value})}/></label>)}<ServiceInventoryRequirements value={draft.inventory_requirements} onChange={items=>setDraft(previous=>({...previous,inventory_requirements:items}))}/>{error&&<p role="alert">{error}</p>}<button type="button" disabled={busy||!draft.nombre.trim()} onClick={create} className="accent-fill rounded-xl px-3 py-2">{busy?'Guardando…':'Guardar y seleccionar'}</button></div>}</section>;
}
