'use strict';
const {test}=require('node:test');const assert=require('node:assert/strict');
const {profileFromRaw}=require('../src/domain/worldoffice-client-profile');
const {normalizeServiceSite}=require('../src/domain/service-site');
const {extractClients,identifier}=require('../src/services/worldoffice-client-extraction.service');
const site={mode:'customer',address:'Carrera 1 # 2-3',city:'Barranquilla',latitude:10.9,longitude:-74.8,radius_m:150,confirmed:true};
test('reconoce contacto con nombres variables y conserva el origen sin mutarlo',()=>{const raw={IdTercero:1,'Teléfono':' 555 ',CorreoElectronico:'a@example.com','Dirección':'Calle 1',CampoIrrelevante:false,Otro:null};const copy=structuredClone(raw);const p=profileFromRaw(raw);assert.equal(p.telefono,'555');assert.equal(p.email,'a@example.com');assert.equal(p.direccion,'Calle 1');assert.deepEqual(raw,copy);});
test('obtiene contactos y ciudad desde registros relacionados',()=>{const p=profileFromRaw({IdTercero:1},{'dbo.TercerosContactos (1)':[{Telefono:'555',Email:'a@example.com'}],'dbo.Ciudades (2)':[{Id:5,Nombre:'Barranquilla'}]});assert.equal(p.telefono,'555');assert.equal(p.ciudad,'Barranquilla');});
test('el punto exige dirección, coordenadas y confirmación explícita',()=>{assert.deepEqual(normalizeServiceSite(site).latitude,10.9);for(const patch of [{address:''},{latitude:''},{longitude:null},{latitude:91},{radius_m:24},{confirmed:false},{confirmed:'true'}])assert.throws(()=>normalizeServiceSite({...site,...patch}));assert.equal(normalizeServiceSite(null),null);assert.equal(normalizeServiceSite({...site,latitude:0,longitude:0}).latitude,0);});
test('admite taller y otra sede y rechaza una modalidad desconocida',()=>{assert.equal(normalizeServiceSite({...site,mode:'workshop'}).mode,'local');assert.equal(normalizeServiceSite({...site,mode:'other'}).mode,'external');assert.throws(()=>normalizeServiceSite({...site,mode:'invalid'}));});
test('extracción usa todos los campos y relaciones declaradas sin perder valores',async()=>{const row={IdTercero:1,Identificacion:'123',CampoRaro:0,Direccion:null,Activo:-1};const queries=[];const connection={request(){return{async query(sql){queries.push(sql);if(sql==='SELECT * FROM Terceros')return{recordset:[row]};if(sql.includes('sys.foreign_keys'))return{recordset:[{relation_id:1,parent_schema:'dbo',parent_table:'TercerosContactos',parent_column:'IdTercero',reference_schema:'dbo',reference_table:'Terceros',reference_column:'IdTercero',direction:'incoming'}]};return{recordset:[{__wo_owner_id:1,IdContacto:2,Telefono:'555',CampoContacto:false}]};}}}};const result=await extractClients(connection);assert.deepEqual(result[0],row);assert.equal(result.profiles.get('1').normalized.telefono,'555');assert.equal(result.profiles.get('1').relations['dbo.TercerosContactos (1)'][0].CampoContacto,false);assert.ok(queries[2].includes('r.*'));assert.ok(result.profileSchema.fields.includes('CampoRaro'));});
test('un resultado vacío se rechaza para conservar el espejo anterior',async()=>{await assert.rejects(extractClients({request(){return{query:async()=>({recordset:[]})}}}));});
test('los identificadores de tablas proceden del catálogo y se escapan',()=>{assert.equal(identifier('Mi]Tabla'),'[Mi]]Tabla]');});
test('coordenadas copiadas y enlaces completos identifican un punto',async()=>{const {parseServicePoint}=await import('../../frontend/src/pages/Dashboard/servicios/serviceLocation.js');assert.deepEqual(parseServicePoint('10.9, -74.8'),{latitude:10.9,longitude:-74.8});assert.deepEqual(parseServicePoint('https://maps.google.com/?q=10.9,-74.8'),{latitude:10.9,longitude:-74.8});assert.deepEqual(parseServicePoint('https://www.google.com/maps/place/Test/data=!3d10.9!4d-74.8'),{latitude:10.9,longitude:-74.8});assert.equal(parseServicePoint('https://maps.app.goo.gl/short'),null);assert.equal(parseServicePoint('https://www.google.com/maps/@10.9,-74.8,15z'),null);assert.equal(parseServicePoint('91,0'),null);});

test('remoto y local no requieren coordenadas ni conservan puntos ocultos',()=>{for(const mode of ['remote','local']){const value=normalizeServiceSite({mode,latitude:10,longitude:-74});assert.equal(value.mode,mode);assert.equal(value.latitude,null);assert.equal(value.longitude,null);}});

const {custodyRequiresLocation}=require('../src/domain/service-site');
test('la custodia exige GPS para visita externa y legado, y respeta remoto/local y la configuración',()=>{for(const mode of ['local','remote','workshop'])assert.equal(custodyRequiresLocation({mode}),false);for(const mode of ['external','customer','other'])assert.equal(custodyRequiresLocation({mode}),true);assert.equal(custodyRequiresLocation(null),true);assert.equal(custodyRequiresLocation({mode:'external'},false),false);});
