'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),path=require('node:path'),{pathToFileURL}=require('node:url'),fs=require('node:fs'),vm=require('node:vm'),{createRequire}=require('node:module');
const {cleanProductImages}=require('../src/domain/product-images');
const png='data:image/png;base64,iVBORw0KGgo=';
test('Fotos persistentes admiten objetos, cadenas y listas JSON sin perder contenido',()=>{assert.equal(cleanProductImages([png])[0].url,png);assert.equal(cleanProductImages(JSON.stringify([{url:png,name:'Martillo'}]))[0].name,'Martillo');assert.equal(cleanProductImages([{path:'/api/products/photo'}])[0].url,'/api/products/photo');});
test('No guarda enlaces temporales ni formatos ejecutables como fotos',()=>{assert.throws(()=>cleanProductImages([{url:'blob:http://localhost/old'}]),e=>e.status===400&&/temporal/.test(e.message));assert.throws(()=>cleanProductImages(['javascript:alert(1)']),e=>e.status===400);});
test('Resolver frontend conserva base64 y resuelve rutas contra backend',async()=>{global.window={location:{origin:'https://tecnicos.example'}};const {inventoryImages,inventoryImageSource}=await import(pathToFileURL(path.resolve(__dirname,'../../frontend/src/pages/Dashboard/inventarios/inventoryImages.js')).href);assert.equal(inventoryImages([png])[0].url,png);assert.equal(inventoryImages(JSON.stringify([{url:png}]))[0].url,png);assert.equal(inventoryImageSource('/api/photo','https://api.example').url,'https://api.example/api/photo');assert.equal(inventoryImageSource(png,'https://api.example').url,png);assert.equal(inventoryImageSource('blob:expired','https://api.example').reason,'expired');delete global.window;});
function controller(name,pool){const file=path.resolve(__dirname,'../src/controllers/'+name+'.controller.js'),m={exports:{}},req=createRequire(file);vm.runInNewContext(fs.readFileSync(file,'utf8'),{module:m,exports:m.exports,require:n=>n==='../db/pool'?pool:req(n),console,process,Buffer,__dirname:path.dirname(file)});return m.exports;}
const res=()=>({code:200,status(n){this.code=n;return this},json(b){this.body=b;return this}});
test('Editar otros datos del producto conserva imágenes omitidas',async()=>{let values,sql;const ctl=controller('product',{async query(s,v){sql=s;values=v;return{rows:[{id:'p'}]};}}),r=res();await ctl.update({params:{id:'p'},body:{nombre:'Herramienta'}},r);assert.equal(r.code,200);assert.equal(values[10],null);assert.match(sql,/imagenes = COALESCE\(\$11::jsonb,imagenes\)/);});
test('Tablero admin retorna todos los estados y rechaza usuarios técnicos',async()=>{let queries=0;const ctl=controller('service-order',{async query(sql){queries++;assert(!sql.includes("WHERE so.tecnico_id IS NOT NULL"));assert(!sql.includes("so.estado::text NOT IN ('cerrada', 'cancelado', 'rechazado')"));return{rows:[{id:'closed',estado:'cerrada'},{id:'new',tecnico_id:null}]};}});let r=res();await ctl.adminWorkBoard({user:{id:'admin',rol:'admin'}},r);assert.equal(r.body.data.length,2);r=res();await ctl.adminWorkBoard({user:{id:'tech',rol:'tecnico'}},r);assert.equal(r.code,403);assert.equal(queries,1);});
