'use strict';const{test}=require('node:test'),assert=require('node:assert/strict');const{validateTypeIds,prepareServiceTypes}=require('../src/services/order-service-types.service');const{snapshotHash,acceptanceSnapshot,acceptanceHtml}=require('../src/domain/intake-acceptance');
const a='00000000-0000-4000-8000-000000000001',b='00000000-0000-4000-8000-000000000002';
test('selección múltiple rechaza lista vacía, tipos repetidos y referencias inválidas',()=>{for(const ids of [[],[a,a],['x'],null])assert.throws(()=>validateTypeIds(ids),{status:400});assert.deepEqual(validateTypeIds([a,b]),[a,b]);});
test('tipos múltiples suman duración y conservan su inventario individual',async()=>{const db={query:async sql=>sql.includes('FROM tipos_servicio')?{rows:[{id:a,nombre:'Mantenimiento',valor_base:100,duracion_estimada:60},{id:b,nombre:'Instalación',valor_base:200,duracion_estimada:90}]}:{rows:[{service_type_id:a,product_id:b,quantity:1},{service_type_id:b,product_id:b,quantity:2}]}};const body={service_type_ids:[a,b]};const types=await prepareServiceTypes(db,body);assert.equal(body.estimated_duration,150);assert.equal(body.base_value,300);assert.equal(types.length,2);assert.equal(types[1].inventory_requirements[0].quantity,2);});
test('editar un dato ajeno a los tipos conserva sus condiciones e inventario originales',async()=>{const types=[{id:a,nombre:'Original',duracion_estimada:60,valor_base:10,inventory_requirements:[]}];const db={query(){throw Error('No debe refrescar un catálogo que pudo cambiar');}};const body={service_type_ids:[a],base_value:25};assert.equal(await prepareServiceTypes(db,body,{service_types:types}),types);assert.equal(body.base_value,25);});
test('tipo ausente y duración total excesiva se rechazan',async()=>{await assert.rejects(()=>prepareServiceTypes({query:async()=>({rows:[]})},{service_type_ids:[a,b]}),{status:400});await assert.rejects(()=>prepareServiceTypes({}, {service_type_ids:[a,b]},{service_types:[{id:a,duracion_estimada:1000},{id:b,duracion_estimada:1000}]}),{status:400});});
test('acta detalla tipos incluidos y cambiar la lista invalida la firma',()=>{const i={service_types:[{id:a,nombre:'Mantenimiento',duracion_estimada:60,valor_base:100,inventory_requirements:[]},{id:b,nombre:'Instalación',duracion_estimada:90,valor_base:200,inventory_requirements:[]}]};assert.notEqual(snapshotHash(i),snapshotHash({...i,service_types:i.service_types.slice(0,1)}));const html=acceptanceHtml(acceptanceSnapshot(i),'firma','Hoy');assert.match(html,/Mantenimiento · 60 minutos/);assert.match(html,/Instalación · 90 minutos/);});
function editFixture({allocated=false,conflict=false}={}){
 const fs=require('fs'),vm=require('vm'),path=require('path'),{createRequire}=require('module');const calls=[];let scheduled=0;
 const db={release(){},async query(sql,params){calls.push({sql,params});if(sql.includes('FROM service_orders')&&sql.includes('FOR UPDATE'))return{rows:[{id:a,estado:'asignada',tecnico_id:b,duracion_estimada:60}]};if(sql.includes('SELECT *')&&sql.includes('FROM service_order_intakes'))return{rows:[{id:b,billing_mode:'prepaid',service_types:[{id:a,nombre:'Mantenimiento',duracion_estimada:60,valor_base:100}]}]};if(sql.includes('SELECT 1 FROM service_inventory_allocations'))return{rows:allocated?[{one:1}]:[]};if(sql.includes('FROM tipos_servicio'))return{rows:[{id:a,nombre:'Mantenimiento',duracion_estimada:60,valor_base:100},{id:b,nombre:'Instalación',duracion_estimada:90,valor_base:200}]};if(sql.includes('SELECT billing_mode, invoice_reference'))return{rows:[]};return{rows:[]};}};
 const controller={},file=path.resolve(__dirname,'../src/controllers/service-order.controller.js'),real=createRequire(file);const schedule=async()=>{scheduled++;if(conflict)throw Object.assign(new Error('Otro técnico está ocupado'),{code:'SCHEDULE_CONFLICT'});return{duration_minutes:150};};vm.runInNewContext(fs.readFileSync(file,'utf8'),{exports:controller,require:n=>n==='../db/pool'?{connect:async()=>db,query:db.query}:n==='../services/service-scheduling.service'?{scheduleOrderAutomatically:schedule,rescheduleOrderAt:schedule}:real(n),console:{error(){}},process,Buffer,__dirname:path.dirname(file)});return{controller,calls,scheduled:()=>scheduled};
}
async function edit(f){const r={code:200,status(n){this.code=n;return this},json(v){this.data=v;return this}};await f.controller.update({params:{id:a},user:{id:b,rol:'admin'},body:{service_type_ids:[a,b],scheduling_mode:'auto'}},r);return r;}
test('edición guarda una fila por tipo y vuelve a reservar la duración total',async()=>{const f=editFixture(),r=await edit(f);assert.equal(r.code,200,JSON.stringify(r.data));assert.equal(f.calls.filter(c=>c.sql.includes('INSERT INTO service_order_services')).length,2);assert.equal(f.scheduled(),1);assert(f.calls.some(c=>c.sql==='COMMIT'));assert.equal(f.calls.find(c=>c.sql.includes('UPDATE service_orders SET duracion_estimada')).params[1],150);});
test('un cruce al extender los tipos revierte la edición completa',async()=>{const f=editFixture({conflict:true}),r=await edit(f);assert.equal(r.code,409);assert(f.calls.some(c=>c.sql==='ROLLBACK'));assert(!f.calls.some(c=>c.sql==='COMMIT'));});
test('no cambia tipos ni inventario previsto después de que el técnico recibió los artículos',async()=>{const f=editFixture({allocated:true}),r=await edit(f);assert.equal(r.code,409);assert(!f.calls.some(c=>c.sql.includes('DELETE FROM service_order_services')));assert(f.calls.some(c=>c.sql==='ROLLBACK'));});
