'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),{createRequire}=require('node:module');
function helper(controller,name){const file=path.join(__dirname,'../src/controllers/'+controller+'.controller.js'),m={exports:{}};vm.runInNewContext(fs.readFileSync(file,'utf8')+'\nmodule.exports.testHelper='+name+';',{module:m,exports:m.exports,require:createRequire(file),console,process,Buffer,__dirname:path.dirname(file)});return m.exports.testHelper;}
const extra=helper('service-delivery','extraDeliveryRequirement');
function client(rows,control){return{async query(sql){if(sql.includes('service_order_authorizations'))return{rows};if(sql.includes('COUNT'))return{rows:[{total:1}]};if(sql.includes('service_order_financial_controls'))return{rows:[control]};return{rows:[]};}};}
test('Servicio principal permite entrega sin consulta financiera',async()=>{let queries=0;const c={async query(sql){queries++;assert(sql.includes('service_order_authorizations'));return{rows:[]};}};const r=await extra(c,'os');assert.equal(r.ready,true);assert.equal(r.required,false);assert.equal(queries,1);});
test('Servicio extra pendiente de autorización bloquea entrega',async()=>{const r=await extra(client([{status:'pending',estimated_amount:0}]),'os');assert.equal(r.authorization_pending,true);assert.equal(r.ready,false);});
test('Extra gratuito aprobado permite entrega',async()=>{assert.equal((await extra(client([{status:'approved',estimated_amount:0}]),'os')).ready,true);});
test('Cobro extra exige verificación posterior a aprobación',async()=>{const rows=[{status:'approved',estimated_amount:10000,decided_at:'2026-10-08T12:00:00Z'}],control={clearance_status:'cleared',verification_required:true,last_verified_at:'2026-10-08T11:00:00Z'};assert.equal((await extra(client(rows,control),'os')).ready,false);control.last_verified_at='2026-10-08T13:00:00Z';assert.equal((await extra(client(rows,control),'os')).ready,true);});
const prereq=helper('service-document','assertPrerequisites');
test('Técnico puede generar acta final con entrega confirmada',()=>{assert.doesNotThrow(()=>prereq({user:{rol:'tecnico'}},'final_delivery',{delivery:{status:'delivered'}}));assert.throws(()=>prereq({user:{rol:'tecnico'}},'final_delivery',{delivery:{status:'draft'}}),e=>e.code==='FINAL_DELIVERY_REQUIRED');});
test('Acta técnica disponible al confirmar trabajo sin paso por Dirección',()=>{assert.doesNotThrow(()=>prereq({},'technical_closure',{closure:{status:'technical_closed'}}));assert.throws(()=>prereq({},'technical_closure',{closure:{status:'draft'}}),e=>e.code==='TECHNICAL_CLOSURE_REQUIRED');});
