'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {prepareReactivation}=require('../src/services/service-reactivation.service');
const {resolveTarget,connectionFailure}=require('../src/services/worldoffice-connection-config');
function db({delivery=[],closure=[],pending=[]}={}){const calls=[];return {calls,query:async(s,v)=>{calls.push({s,v});return {rows:s.includes('service_order_deliveries')?delivery:s.includes('service_order_closures')?closure:s.includes('workshop_assignments')?pending:[]}}};}
test('Reactivation preserves history and clears acceptance marker only after inventory is settled',async()=>{const c=db();await prepareReactivation(c,{id:'os',estado:'cancelado'},'Cliente solicita continuar');assert.equal(c.calls.at(-1).s,'DELETE FROM service_inventory_allocations WHERE service_order_id=$1');assert(!c.calls.some(q=>/DELETE FROM (workshop_events|service_order_events|workshop_assignments)/.test(q.s)));});
test('Missing reason, completed delivery/closure and outstanding tools reject reactivation without changing stock',async()=>{for(const params of [{delivery:[{status:'delivered'}]},{closure:[{status:'validated'}]},{pending:[{id:'tool'}]}]){const c=db(params);await assert.rejects(()=>prepareReactivation(c,{id:'os',estado:'cancelado'},'Continuar'),e=>e.status===409);assert(!c.calls.some(q=>q.s.startsWith('DELETE')));}await assert.rejects(()=>prepareReactivation(db(),{id:'os',estado:'cancelado'},''),e=>e.status===400);await assert.rejects(()=>prepareReactivation(db(),{id:'os',estado:'cerrada'},'Continuar'),e=>e.status===409);});
test('Windows discovers a verified TCP target, retaining SQL options without SQL Browser',async()=>{const c={server:'tecnoserver',user:'u',password:'secret',database:'Melissa',options:{instanceName:'WORLDOFFICE22',encrypt:true}};const r=await resolveTarget(c,{platform:'win32',nativeResolve:async()=>({server:'192.168.1.4',port:51234}),lookup:()=>{throw new Error('DNS must not run')}});assert.equal(r.server,'192.168.1.4');assert.equal(r.port,51234);assert.equal(r.options.instanceName,undefined);assert.equal(r.options.encrypt,true);assert.equal(c.options.instanceName,'WORLDOFFICE22');});
test('Native failure keeps normal DNS path and resolves IP rather than requiring a second DNS query',async()=>{const c={server:'server',user:'u',password:'secret',options:{instanceName:'SQL'}};const r=await resolveTarget(c,{platform:'win32',nativeResolve:async()=>{throw new Error('offline')},lookup:async()=>({address:'192.168.1.8'})});assert.equal(r.server,'192.168.1.8');assert.equal(r.options.instanceName,'SQL');assert.equal(connectionFailure({code:'EINSTLOOKUP'},'server').code,'WORLDOFFICE_CONNECTION_UNAVAILABLE');});
const fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),{createRequire}=require('node:module');
const uid=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
async function assign({state='cancelado',scheduleFails=false,role='admin',reactivate=true,latest='revocada'}={}){
 const queries=[],client={release(){},async query(s,args){queries.push(s);if(s.includes('FROM usuarios u'))return{rows:[{id:uid(2),activo:true,rol:'tecnico'}]};if(s.includes('FROM service_orders'))return{rows:[{id:uid(1),estado:state}]};if(s.includes('FROM service_order_assignments'))return{rows:[{status:latest}]};if(s.includes('RETURNING *'))return{rows:[{id:uid(1),estado:'asignada'}]};return{rows:[]}}};
 const file=path.join(__dirname,'../src/controllers/service-team.controller.js'),m={exports:{}},localRequire=createRequire(file);
 vm.runInNewContext(fs.readFileSync(file,'utf8'),{module:m,exports:m.exports,require:n=>n==='../db/pool'?{connect:async()=>client}:n==='../services/service-scheduling.service'?{scheduleOrderAutomatically:async()=>{if(scheduleFails)throw Object.assign(new Error('Sin disponibilidad'),{code:'NO_COMMON_SLOT'});return{start_at:'2026-10-09T14:00:00Z'}}}:localRequire(n),process,console:{error(){}},Buffer});
 const res={code:200,status(c){this.code=c;return this},json(b){this.body=b;return this}};
 await m.exports.assignPrimary({params:{id:uid(1)},body:{tecnico_id:uid(2),reactivate,reason:'Volver a prestar servicio'},user:{id:uid(3),rol:role}},res);return{res,queries};
}
test('Controller commits cancellation reactivation with new assignment/schedule and audit; a schedule conflict rolls back everything',async()=>{const good=await assign();assert.equal(good.res.code,200);assert(good.queries.includes('COMMIT'));assert(good.queries.some(q=>q.includes('INSERT INTO service_order_assignments')));const bad=await assign({scheduleFails:true});assert.equal(bad.res.code,409);assert(bad.queries.includes('ROLLBACK'));assert(!bad.queries.includes('COMMIT'));});
test('Revoked assignments can be reassigned, but technicians and closed orders cannot reopen orders',async()=>{assert.equal((await assign({state:'asignada',reactivate:false})).res.code,200);assert.equal((await assign({role:'tecnico'})).res.code,403);assert.equal((await assign({state:'cerrada'})).res.code,409);assert.equal((await assign({reactivate:false})).res.code,409);});
