'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),{createRequire}=require('node:module'),path=require('node:path');
const id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
function controller(){const queries=[],client={release(){},async query(sql,args){queries.push({sql,args});if(sql.includes('FROM service_orders'))return{rows:[{id:id(1),estado:'asignada',tecnico_id:id(2),creator_id:id(3)}]};if(sql.includes('FROM service_order_team_members'))return{rows:[]};if(sql.includes('SELECT sm.*')&&sql.includes('servicio_materiales'))return{rows:[{id:id(5),service_order_id:id(1),estado:'solicitado',cantidad_solicitada:2,external_name:'Cable especial'}]};if(sql.includes('RETURNING'))return{rows:[{id:id(5)}]};return{rows:[]};}},pool={...client,connect:async()=>client},file=path.join(__dirname,'../src/controllers/material.controller.js'),m={exports:{}},req=createRequire(file);vm.runInNewContext(fs.readFileSync(file,'utf8'),{module:m,exports:m.exports,require:n=>n==='../db/pool'?pool:req(n),console,process});return{ctl:m.exports,queries};}
async function call(ctl,name,{actor=id(2),body={},params={service_order_id:id(1)}}={}){const res={code:200,status(n){this.code=n;return this},json(b){this.body=b;return this}};await ctl[name]({params,body,user:{id:actor,rol:'tecnico'}},res);return res;}
test('Solicitud externa conserva datos sin descontar stock',async()=>{const{ctl,queries}=controller();const r=await call(ctl,'solicitarMateriales',{body:{external_name:' Cable especial ',external_description:'3 metros',cantidad:2}});assert.equal(r.code,201);const insert=queries.find(q=>q.sql.includes('INSERT INTO servicio_materiales'));assert.equal(insert.args[2],null);assert.equal(insert.args[3],2);assert.equal(insert.args[6],'Cable especial');assert.equal(insert.args[7],'3 metros');assert(!queries.some(q=>q.sql.includes('UPDATE products')));const event=queries.find(q=>q.sql.includes('INSERT INTO service_order_events'));assert.match(JSON.parse(event.args[4]).summary,/2 × Cable especial/);});
test('Asignado solicita pero solo creador o administración decide',async()=>{const{ctl}=controller();assert.equal((await call(ctl,'aprobarMaterial',{params:{id:id(5)}})).code,403);assert.equal((await call(ctl,'aprobarMaterial',{actor:id(3),params:{id:id(5)}})).code,200);});
test('Orden ajena y cantidades fraccionarias se rechazan',async()=>{const{ctl}=controller();assert.equal((await call(ctl,'solicitarMateriales',{actor:id(9),body:{external_name:'Cable',cantidad:2}})).code,403);assert.equal((await call(ctl,'solicitarMateriales',{body:{external_name:'Cable',cantidad:1.5}})).code,400);assert.equal((await call(ctl,'aprobarMaterial',{actor:id(3),params:{id:id(5)},body:{cantidad:1.5}})).code,400);});
test('Exige catálogo o nombre externo y rechaza ambos a la vez',async()=>{const{ctl}=controller();assert.equal((await call(ctl,'solicitarMateriales',{body:{cantidad:2}})).code,400);assert.equal((await call(ctl,'solicitarMateriales',{body:{product_id:id(4),external_name:'Cable',cantidad:2}})).code,400);});
