'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),{createRequire}=require('node:module'),path=require('node:path');const id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
function controller({fence=true,location=null,holder=null,accepted=true}={}){const visits=[];const queries=[],client={release(){},async query(sql,args){queries.push({sql,args});if(sql.includes('FROM service_order_visit_events'))return{rows:visits.filter(v=>!sql.includes("IN ('llegada_declarada'")||v.event_type!=='en_camino')};if(sql.includes('INSERT INTO service_order_visit_events'))visits.push({event_type:sql.includes("'en_camino'")?'en_camino':sql.includes("'llegada_validada'")?'llegada_validada':'llegada_declarada'});if(sql.includes('FROM service_orders'))return{rows:[{id:id(1),codigo_os:'OS-TEST',estado:'asignada',tecnico_id:id(2),service_site:{mode:'external'}}]};if(sql.includes('FROM service_order_assignments'))return{rows:[{tecnico_id:id(2),status:accepted?'aceptada':'pendiente'}]};if(sql.includes('FROM user_current_locations'))return{rows:location?[location]:[]};if(sql.includes('FROM service_order_geofences'))return{rows:fence?[{latitude:10,longitude:-74,radius_m:150}]:[]};if(sql.includes('FROM service_order_current_custody'))return{rows:holder?[{holder_user_id:holder}]:[]};if(sql.includes('RETURNING'))return{rows:[{holder_user_id:id(2)}]};return{rows:[]};}},pool={...client,connect:async()=>client},file=path.join(__dirname,'../src/controllers/service-order.controller.js'),m={exports:{}},req=createRequire(file);vm.runInNewContext(fs.readFileSync(file,'utf8'),{module:m,exports:m.exports,require:n=>n==='../db/pool'?pool:req(n),console,process,Buffer,__dirname:path.dirname(file)});return{ctl:m.exports,queries};}
async function call(ctl,name,actor=id(2)){const r={code:200,status(n){this.code=n;return this},json(b){this.body=b;return this}};await ctl[name]({params:{id:id(1)},body:{},user:{id:actor,rol:'tecnico'}},r);return r;}
test('Visita con punto configurado permite llegada sin GPS y no inventa validación',async()=>{const{ctl,queries}=controller();const r=await call(ctl,'markArrived');assert.equal(r.code,200);assert.equal(r.body.gps_verified,false);assert(queries.some(q=>q.sql.includes("'llegada_declarada'")));});
test('GPS fuera del radio conserva llegada declarada y distancia',async()=>{const{ctl,queries}=controller({location:{latitude:11,longitude:-74,accuracy_m:10}});const r=await call(ctl,'markArrived');assert.equal(r.code,200);assert.equal(r.body.gps_verified,false);assert(queries.some(q=>q.sql.includes("'llegada_declarada'")&&q.args?.length===7));});
test('Custodia sin GPS sigue exigiendo aceptación y responsable correcto',async()=>{let c=controller();let r=await call(c.ctl,'takeCustody');assert.equal(r.code,200);assert.equal(r.body.precise_location_recorded,false);const insert=c.queries.find(q=>q.sql.includes('INSERT INTO service_order_current_custody'));assert.equal(insert.args[2],null);c=controller({accepted:false});assert.equal((await call(c.ctl,'takeCustody')).code,409);c=controller();assert.equal((await call(c.ctl,'takeCustody',id(9))).code,403);c=controller({holder:id(9)});assert.equal((await call(c.ctl,'takeCustody')).code,409);});

test('En camino y llegada solo registran una vez y llegada bloquea un En camino tardío',async()=>{let c=controller();let r=await call(c.ctl,'markEnRoute');assert.equal(r.code,200);r=await call(c.ctl,'markEnRoute');assert.equal(r.body.already_recorded,true);r=await call(c.ctl,'markArrived');assert.equal(r.code,200);r=await call(c.ctl,'markArrived');assert.equal(r.body.already_recorded,true);assert.equal(c.queries.filter(q=>q.sql.includes('INSERT INTO service_order_visit_events')).length,2);c=controller();await call(c.ctl,'markArrived');r=await call(c.ctl,'markEnRoute');assert.equal(r.body.already_recorded,true);assert.equal(c.queries.filter(q=>q.sql.includes('INSERT INTO service_order_visit_events')).length,1);});
