'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),{createRequire}=require('node:module');
const id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
function fixture(){const queries=[],files=new Map(),a={id:id(3),service_order_id:id(1),technician_id:id(2),product_id:id(4),quantity:2,returned_quantity:0,consumed_quantity:0};const client={release(){},async query(sql,args){queries.push({sql,args});if(sql.includes('FROM service_orders'))return{rows:[{id:id(1),tecnico_id:id(2)}]};if(sql.includes('FROM workshop_assignments'))return{rows:[a]};if(sql.includes("SELECT id,metadata FROM workshop_events"))return{rows:[{id:id(5),metadata:{photo_ids:[]}}]};if(sql.includes('SELECT id FROM workshop_return_photos'))return{rows:args[1].map(id=>({id}))};if(sql.includes('SELECT e.metadata'))return{rows:[{metadata:{photo_ids:[id(6)]},service_order_id:id(1)}]};if(sql.includes('SELECT storage_path,mime_type'))return{rows:[{storage_path:'test/photo.png',mime_type:'image/png'}]};return{rows:[]};}};const pool={connect:async()=>client},file=path.join(__dirname,'../src/controllers/workshop.controller.js'),req=createRequire(file),m={exports:{}};vm.runInNewContext(fs.readFileSync(file,'utf8'),{module:m,exports:m.exports,require:n=>n==='../db/pool'?pool:n==='fs/promises'?{mkdir:async()=>{},writeFile:async(p,b)=>files.set(p,b),unlink:async p=>files.delete(p),access:async()=>{}}:req(n),console,process,Buffer,__dirname:path.dirname(file)});return{ctl:m.exports,queries,files};}
async function call(ctl,name,{actor=id(2),body={},params={id:id(3)},query={},bytes,mime='image/png'}={}){const res={code:200,status(n){this.code=n;return this},json(b){this.body=b;return this},setHeader(){},sendFile(p){this.path=p;return this}};await ctl[name]({user:{id:actor,rol:'tecnico'},params,body,query,headers:{'content-type':mime},async *[Symbol.asyncIterator](){if(bytes)yield bytes}},res);return res;}
const png=Buffer.from([137,80,78,71,13,10,26,10,1]);
test('Devolución sin fotos sigue compatible y registra actor y cantidades',async()=>{const f=fixture();const r=await call(f.ctl,'returnItem',{body:{quantity:1}});assert.equal(r.code,200);const event=f.queries.find(q=>q.sql.includes("VALUES($1,'returned'"));assert.equal(event.args[2],id(2));assert.deepEqual(JSON.parse(event.args[4]).photo_ids,[]);assert(f.queries.some(q=>q.sql.includes('stock_actual=stock_actual+$2')&&q.args[1]===1));});
test('La foto histórica registra vínculo al movimiento y autor sin descontar stock',async()=>{const f=fixture();const r=await call(f.ctl,'uploadReturnPhoto',{bytes:png,query:{event_id:id(5)}});assert.equal(r.code,201);assert.equal(f.files.size,1);const update=f.queries.find(q=>q.sql.startsWith('UPDATE workshop_events'));assert(JSON.parse(update.args[1]).photo_ids.includes(r.body.id));assert(f.queries.some(q=>q.sql.includes('INSERT INTO workshop_return_photos')&&q.args[2]===id(2)));assert(!f.queries.some(q=>q.sql.includes('UPDATE products')));});
test('Fotos de devolución rechazan formato falso y técnico ajeno',async()=>{const f=fixture();assert.equal((await call(f.ctl,'uploadReturnPhoto',{bytes:Buffer.from('false')})).code,415);assert.equal((await call(f.ctl,'uploadReturnPhoto',{actor:id(9),bytes:png})).code,403);assert.equal(f.files.size,0);});
test('Abrir evidencia requiere pertenecer al servicio y que foto corresponda al movimiento',async()=>{const f=fixture();assert.equal((await call(f.ctl,'getEventPhoto',{params:{eventId:id(5),photoId:id(6),source:'return'}})).code,200);assert.equal((await call(f.ctl,'getEventPhoto',{params:{eventId:id(5),photoId:id(9),source:'return'}})).code,404);assert.equal((await call(f.ctl,'getEventPhoto',{actor:id(9),params:{eventId:id(5),photoId:id(6),source:'return'}})).code,403);});
test('Historial de un producto aplica filtro a asignaciones y movimientos',async()=>{const f=fixture();const r=await call(f.ctl,'list',{query:{product_id:id(4)}});assert.equal(r.code,200);const scoped=f.queries.filter(q=>q.sql.includes('a.product_id=$4'));assert.equal(scoped.length,2);assert(scoped.every(q=>q.args[3]===id(4)));});
