'use strict';
async function creationAvailability(db,{date,time,typeId,typeIds,technicians=[],excludeOrder=null}){
 if(!/^\d{4}-\d{2}-\d{2}$/.test(date||'')||!/^([01]\d|2[0-3]):[0-5]\d$/.test(time||''))throw Object.assign(new Error('Selecciona fecha y hora de Colombia.'),{status:400});
 if(!Array.isArray(technicians)||!technicians.length||technicians.length>20||technicians.some(id=>!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(id)))throw Object.assign(new Error('Selecciona un equipo técnico válido.'),{status:400});
 const ids=require('./order-service-types.service').validateTypeIds(typeIds||[typeId]);const types=(await db.query('SELECT id,duracion_estimada FROM tipos_servicio WHERE id=ANY($1::uuid[]) AND activo=true',[ids])).rows;if(types.length!==ids.length)throw Object.assign(new Error('Selecciona tipos de servicio activos.'),{status:400});const type={duracion_estimada:types.reduce((sum,t)=>sum+Number(t.duracion_estimada||60),0)};if(type.duracion_estimada>1440)throw Object.assign(new Error('La duración total supera 1440 minutos.'),{status:400});
 const start=Date.parse(date+'T'+time+':00-05:00'),end=start+Number(type.duracion_estimada||60)*60000;if(!Number.isFinite(start)||new Date(start-5*3600000).toISOString().slice(0,10)!==date)throw Object.assign(new Error('Fecha no válida.'),{status:400});
 const busy=(await db.query(`SELECT b.technician_id,b.start_at,b.end_at,b.service_order_id,so.codigo_os FROM service_order_schedule_blocks b JOIN service_orders so ON so.id=b.service_order_id WHERE b.technician_id=ANY($1::uuid[]) AND b.status='active' AND b.start_at<$3::timestamptz AND b.end_at>$2::timestamptz AND ($4::uuid IS NULL OR b.service_order_id<>$4::uuid)`,[technicians,new Date(start).toISOString(),new Date(end).toISOString(),excludeOrder])).rows;
 const results=technicians.map(id=>{const conflicts=busy.filter(b=>b.technician_id===id);return {technician_id:id,available:!conflicts.length,reason:(conflicts.length?'Ya tiene otro servicio en ese intervalo: '+conflicts.map(b=>b.codigo_os).join(', '):null),reason_code:conflicts.length?'SCHEDULE_CONFLICT':null,conflicts};});return{available:results.every(t=>t.available),duration:Number(type.duracion_estimada||60),technicians:results};
}
module.exports={creationAvailability};
