'use strict';
const pool=require('../db/pool');
function period(input={}){const today=new Date(Date.now()-5*3600000).toISOString().slice(0,10);const from=input.from||new Date(Date.now()-5*3600000-29*86400000).toISOString().slice(0,10),to=input.to||today;const valid=s=>/^\d{4}-\d{2}-\d{2}$/.test(s)&&!Number.isNaN(new Date(s+'T12:00:00Z').getTime())&&new Date(s+'T12:00:00Z').toISOString().slice(0,10)===s;if(!valid(from)||!valid(to)||from>to||(new Date(to)-new Date(from))/86400000>366)throw Object.assign(new Error('Selecciona un período válido de hasta 366 días.'),{status:400});return{from,to};}
async function getOperations(req){const range=period(req.query);const role=req.user?.role?.name||req.user?.rol;const admin=role==='admin';if(!['admin','tecnico','inventario'].includes(role))throw Object.assign(new Error('No autorizado para este dashboard'),{status:403});
const c=await pool.connect();try{await c.query('BEGIN ISOLATION LEVEL REPEATABLE READ READ ONLY');
const result=await c.query(`SELECT so.id,so.codigo_os,so.estado,so.client_id,so.tecnico_id,so."createdAt" AS created_at,so.fecha_inicio,so.fecha_fin,so.duracion_estimada,
 COALESCE(NULLIF(cl.razon_social,''),concat_ws(' ',cl.primer_nombre,cl.primer_apellido),'Sin cliente') AS client_name,concat_ws(' ',u.nombre1,u.apellidos) AS technician,
 closure.status AS closure_status,closure.technical_closed_at,closure.rework_count,closure.actual_minutes,closure.estimated_minutes,
 fc.clearance_status,fc.expected_amount,COALESCE(bill.total,0) AS invoiced
 FROM service_orders so LEFT JOIN clients cl ON cl.id=so.client_id LEFT JOIN usuarios u ON u.id=so.tecnico_id
 LEFT JOIN service_order_closures closure ON closure.service_order_id=so.id LEFT JOIN service_order_financial_controls fc ON fc.service_order_id=so.id
 LEFT JOIN(SELECT service_order_id,SUM(CASE WHEN tipo_documento::text='nota_credito' THEN -total_general ELSE total_general END) AS total FROM invoices WHERE estado::text IN ('emitida','pagada') GROUP BY service_order_id)bill ON bill.service_order_id=so.id
 WHERE so."createdAt">=($1::date::timestamp AT TIME ZONE 'America/Bogota') AND so."createdAt"<(($2::date+1)::timestamp AT TIME ZONE 'America/Bogota')
 AND ($3::boolean OR so.tecnico_id=$4 OR EXISTS(SELECT 1 FROM service_order_team_members tm WHERE tm.service_order_id=so.id AND tm.technician_id=$4 AND tm.member_status<>'removed'))
 ORDER BY so."createdAt" DESC LIMIT 10001`,[range.from,range.to,admin,req.user.id]);
if(result.rows.length>10000)throw Object.assign(new Error('El período supera 10.000 órdenes. Selecciona un rango menor para obtener el detalle completo.'),{status:400});
let inventory=[];if(admin||role==='inventario'){inventory=(await c.query(`SELECT p.id,p.codigo,p.nombre,p.stock_actual,p.stock_minimo,p.costo,w.kind,COALESCE(h.in_use,0) AS in_use FROM products p LEFT JOIN workshop_catalog w ON w.product_id=p.id LEFT JOIN(SELECT product_id,SUM(quantity-returned_quantity-consumed_quantity) AS in_use FROM workshop_assignments GROUP BY product_id)h ON h.product_id=p.id WHERE p.estado=TRUE ORDER BY p.nombre`)).rows;}
const holds=(await c.query(`SELECT a.id,p.nombre,so.codigo_os,concat_ws(' ',u.nombre1,u.apellidos) AS holder,a.quantity-a.returned_quantity-a.consumed_quantity AS quantity,a.created_at FROM workshop_assignments a JOIN products p ON p.id=a.product_id JOIN service_orders so ON so.id=a.service_order_id JOIN usuarios u ON u.id=a.technician_id WHERE a.returned_quantity+a.consumed_quantity<a.quantity AND ($1::boolean OR a.technician_id=$2) ORDER BY a.created_at`,[admin||role==='inventario',req.user.id])).rows;
await c.query('COMMIT');const rows=result.rows.map(r=>({...r,invoiced:admin?Number(r.invoiced):undefined,expected_amount:admin?(r.expected_amount===null?null:Number(r.expected_amount)):undefined}));
const totals={orders:rows.length,active:rows.filter(r=>!['cerrada','cancelado','rechazado'].includes(r.estado)).length,technical_finished:rows.filter(r=>r.technical_closed_at).length,delivered:rows.filter(r=>r.estado==='cerrada').length,reworks:rows.reduce((n,r)=>n+Number(r.rework_count||0),0)};
const months=new Map(),clients=new Map(),techs=new Map();for(const r of rows){const m=new Date(new Date(r.created_at).getTime()-5*3600000).toISOString().slice(0,7);const month=months.get(m)||{month:m,orders:0,finished:0,invoiced:0};month.orders++;month.finished+=r.technical_closed_at?1:0;month.invoiced+=Number(r.invoiced||0);months.set(m,month);
const cl=clients.get(r.client_id)||{client:r.client_name,orders:0,invoiced:0};cl.orders++;cl.invoiced+=Number(r.invoiced||0);clients.set(r.client_id,cl);
const tech=techs.get(r.tecnico_id)||{technician:r.technician||'Sin asignar',orders:0,finished:0,reworks:0,timed:0,on_time:0,actual:0,estimated:0};tech.orders++;tech.finished+=r.technical_closed_at?1:0;tech.reworks+=Number(r.rework_count||0);if(r.actual_minutes!==null&&r.actual_minutes!==undefined){tech.timed++;tech.actual+=Number(r.actual_minutes);tech.estimated+=Number(r.estimated_minutes||r.duracion_estimada||0);tech.on_time+=Number(r.actual_minutes)<=Number(r.estimated_minutes||r.duracion_estimada||0)?1:0;}techs.set(r.tecnico_id,tech);}
const financial=admin?{invoiced:rows.reduce((n,r)=>n+r.invoiced,0),expected:rows.reduce((n,r)=>n+Number(r.expected_amount||0),0),pending:rows.filter(r=>!['cleared','not_required'].includes(r.clearance_status)).length}:null;
const inventoryTotals={items:inventory.length,low_stock:inventory.filter(p=>Number(p.stock_actual)<=Number(p.stock_minimo)).length,available_value:inventory.reduce((n,p)=>n+Number(p.stock_actual)*Number(p.costo||0),0),in_use:holds.reduce((n,h)=>n+Number(h.quantity),0)};
return{range,timezone:'America/Bogota',generated_at:new Date().toISOString(),scope:admin?'Administración':role==='inventario'?'Inventario':'Servicios del equipo y herramientas propias',totals,financial,inventoryTotals,months:[...months.values()].sort((a,b)=>a.month.localeCompare(b.month)),clients:admin?[...clients.values()].sort((a,b)=>b.invoiced-a.invoiced||b.orders-a.orders).slice(0,20):[],technicians:[...techs.values()],inventory,holdings:holds,services:rows};
}catch(e){await c.query('ROLLBACK').catch(()=>{});throw e;}finally{c.release();}}
module.exports={period,getOperations};
