import React,{useCallback,useEffect,useState} from 'react';
import api from '../../../services/api';
import {useAuth} from '../../../hooks/useAuth';
import MaterialesPanel from '../servicios/components/MaterialesPanel';
export default function WorkshopPanel({service=null}){
 const {user}=useAuth();const admin=['admin','inventario'].includes(user?.role?.name||user?.rol);const[data,setData]=useState({products:[],planned:[],assignments:[],events:[]});const[search,setSearch]=useState('');const[error,setError]=useState('');const[busy,setBusy]=useState(false);const[qty,setQty]=useState(1);const[item,setItem]=useState('');const[holder,setHolder]=useState(service?.tecnico_id||user?.id||'');const[users,setUsers]=useState([]);const[tab,setTab]=useState('tools');
 const load=useCallback(async()=>{try{const r=await api.get('/api/workshop',{params:{order_id:service?.id,search}});setData(r.data.data);setError('');}catch(e){setError(e.response?.data?.message||'No fue posible cargar el taller');}},[service?.id,search]);
 useEffect(()=>{const t=setTimeout(load,300);return()=>clearTimeout(t);},[load]);
 useEffect(()=>{if(admin&&service)api.get('/api/usuarios/role/tecnico').then(r=>setUsers(Array.isArray(r.data)?r.data:r.data.data||[])).catch(()=>{});},[admin,service]);
 const run=async(fn)=>{setBusy(true);setError('');try{await fn();await load();return true;}catch(e){setError(e.response?.data?.message||'No fue posible guardar la operación');return false;}finally{setBusy(false);}};
 const exportExcel=async()=>{const XLSX=await import('xlsx');const wb=XLSX.utils.book_new();for(const[name,rows]of Object.entries({Catalogo:data.products.map(p=>({Código:p.codigo,Nombre:p.nombre,Disponible:p.stock_actual,En_uso:p.in_use,Tipo:p.kind==='tool'?'Retornable':p.kind==='supply'?'Insumo':'Sin clasificar'})),Asignaciones:data.assignments.map(a=>({Ítem:a.nombre,Servicio:a.codigo_os,Técnico:a.holder,Cantidad:a.quantity,Devueltos:a.returned_quantity,Consumidos:a.consumed_quantity||0,Pendientes:a.quantity-a.returned_quantity-(a.consumed_quantity||0),Fecha:a.created_at})),Historial:data.events.map(e=>({Fecha:e.created_at,Servicio:e.codigo_os,Ítem:e.nombre,Acción:e.action==='assigned'?'Asignación':e.action==='consumed'?'Consumo':'Devolución',Cantidad:e.quantity,Usuario:e.actor,Nota:e.note}))})){XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rows),name);}XLSX.writeFile(wb,'Inventario-taller.xlsx');};
 const photo=p=>typeof p.photo==='string'?p.photo:p.photo?.url;
 return <div className="workflow-theme space-y-4"><header className="flex flex-wrap justify-between gap-3"><div><h2 className="font-bold text-xl">Inventario de taller</h2><p className="text-sm text-gray-500">Artículos asignados al aceptar, responsable actual e historial. Devuelve herramientas y sobrantes; registra el consumo de los insumos asignados aquí.</p></div><button className="border rounded-xl px-4 py-2" onClick={exportExcel}>Exportar Excel</button></header>{error&&<p role="alert" className="text-red-600">{error}</p>}
 {service&&<div className="flex-wrap flex gap-2"><button onClick={()=>setTab('tools')} className="border rounded-xl p-2">Inventario asignado</button><button onClick={()=>setTab('supplies')} className="border rounded-xl p-2">Solicitar materiales adicionales</button></div>}
 {tab==='supplies'&&service?<MaterialesPanel servicioId={service.id} tecnicoId={service.tecnico_id} isAdmin={admin}/>:<>
 <input aria-label="Buscar ítem de taller" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar por nombre o código" className="w-full border rounded-xl p-3 bg-transparent"/>
 {admin&&!service&&<p className="text-sm">Crea o edita el producto y sus fotos en Inventarios. Aquí clasifícalo como herramienta retornable o insumo para incorporarlo al taller.</p>}
 {service&&<><h3 className="font-bold">Inventario previsto al crear el servicio</h3>{!data.planned?.length&&<p className="text-sm">No hay artículos previstos para los tipos de esta orden.</p>}</>}
 <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">{(service?(data.planned||[]).filter(p=>!search||`${p.nombre} ${p.codigo}`.toLowerCase().includes(search.toLowerCase())):data.products).map(p=><article key={p.id} className="border rounded-xl p-3 flex gap-3">{photo(p)&&<img src={photo(p)} alt={p.nombre} className="w-20 h-20 object-contain rounded" loading="lazy"/>}<div className="min-w-0"><h3 className="font-semibold break-words">{p.nombre}</h3>{service&&<p className="text-sm font-semibold">Previstos: {p.quantity} · Asignados: {data.assignments.filter(a=>a.product_id===p.id).reduce((n,a)=>n+Number(a.quantity),0)}</p>}<p className="text-sm">{p.codigo} · Disponibles {p.stock_actual} · En uso {p.in_use||0}</p>{admin?<select aria-label={'Clasificar '+p.nombre} value={p.kind||''} disabled={busy} onChange={e=>run(()=>api.put('/api/workshop/catalog/'+p.id,{kind:e.target.value}))} className="border p-2 rounded bg-transparent"><option value="" disabled>Sin clasificar</option><option value="tool">Herramienta retornable</option><option value="supply">Insumo</option></select>:<p className="text-sm">{p.kind==='tool'?'Herramienta retornable':p.kind==='supply'?'Insumo':'Clasificación pendiente'}</p>}{admin&&service&&p.kind==='tool'&&<button disabled={busy||p.stock_actual<1} onClick={()=>setItem(p.id)} className="accent-fill rounded-lg p-2 mt-2">Utilizar</button>}</div></article>)}</div>
 {service&&item&&<form className="border rounded-xl p-4 flex flex-wrap gap-3" onSubmit={e=>{e.preventDefault();run(()=>api.post('/api/workshop/assignments',{order_id:service.id,product_id:item,quantity:Number(qty),technician_id:holder})).then(ok=>{if(ok)setItem('');});}}><strong>{data.products.find(p=>p.id===item)?.nombre}</strong><label>Cantidad<input aria-label="Cantidad a utilizar" type="number" min="1" step="1" value={qty} onChange={e=>setQty(e.target.value)} required className="border p-2 rounded bg-transparent w-24 ml-2"/></label>{admin&&<select aria-label="Técnico que recibe" value={holder} onChange={e=>setHolder(e.target.value)} className="border rounded bg-transparent p-2"><option value="">Seleccionar técnico</option>{users.map(u=><option key={u.id} value={u.id}>{[u.nombre1,u.apellidos].filter(Boolean).join(' ')||u.usuario}</option>)}</select>}<button disabled={busy} className="accent-fill rounded-xl px-4 py-2">Registrar uso</button><button type="button" onClick={()=>setItem('')}>Cancelar</button></form>}
 <p className="text-sm">El inventario previsto se asigna una sola vez al técnico principal al aceptar. Registra aquí el consumo de los insumos asignados.</p><h3 className="font-bold">Quién tiene los ítems y cantidades pendientes</h3><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr>{['Ítem','Servicio','Técnico','Asignados','Devueltos','Consumidos','Pendientes','Acción'].map(t=><th key={t} className="p-2 text-left border-b">{t}</th>)}</tr></thead><tbody>{data.assignments.map(a=><tr key={a.id}><td className="p-2">{a.nombre}<span className="block text-xs">{a.item_kind==='supply'?'Insumo':'Herramienta'}</span></td><td>{a.codigo_os}</td><td>{a.holder}</td><td>{a.quantity}</td><td>{a.returned_quantity}</td><td>{a.consumed_quantity||0}</td><td>{a.quantity-a.returned_quantity-(a.consumed_quantity||0)}</td><td>{a.quantity>a.returned_quantity+(a.consumed_quantity||0)&&<button disabled={busy} className="border rounded-lg p-2" onClick={()=>{const n=window.prompt('Cantidad a devolver',String(a.quantity-a.returned_quantity-(a.consumed_quantity||0)));if(n!==null)run(()=>api.post('/api/workshop/assignments/'+a.id+'/return',{quantity:Number(n)}));}}>Devolver</button>}{a.item_kind==='supply'&&a.quantity>a.returned_quantity+(a.consumed_quantity||0)&&<button disabled={busy} className="border rounded-lg p-2 ml-2" onClick={()=>{const n=window.prompt('Cantidad realmente consumida (ya fue descontada al asignar)',String(a.quantity-a.returned_quantity-(a.consumed_quantity||0)));if(n!==null)run(()=>api.post('/api/workshop/assignments/'+a.id+'/consume',{quantity:Number(n)}));}}>Registrar consumo</button>}</td></tr>)}</tbody></table></div>
 <h3 className="font-bold">Historial de uso y devoluciones</h3><ul className="space-y-2">{data.events.map(e=><li key={e.id} className="border rounded-xl p-3 text-sm">{new Intl.DateTimeFormat('es-CO',{dateStyle:'short',timeStyle:'short',timeZone:'America/Bogota'}).format(new Date(e.created_at))} · {e.actor} · {e.action==='assigned'?'Asignó':e.action==='consumed'?'Consumió':'Devolvió'} {e.quantity} × {e.nombre} · {e.codigo_os}{e.note&&<p>{e.note}</p>}</li>)}</ul><p className="text-xs text-gray-500">Catálogo: hasta 100 coincidencias. Historial: últimos 200 movimientos del ámbito visible; Excel exporta estos registros.</p>{service&&<MaterialesPanel servicioId={service.id} allowRequest={false}/>}</>}
 </div>;
}
